import { TowerBlueprint } from "../state/TowerBlueprint";

export const towerBlueprints: TowerBlueprint[] = [
  {
    type: "turret",
    label: "Turret",
    damagePerShot: 20,
    fireRate: 4,
    radius: 1.5,
    price: 50,
    colors: ["#00d89a", "#19ffbd"],
    armorPiercing: false,
    targets: ["air", "ground"],
    rotationSpeed: 3,
    barrelWidth: 3,
    barrelLength: 9,
  },
  {
    type: "flamethrower",
    label: "Flamethrower",
    damagePerShot: 1.5,
    fireRate: 100,
    radius: 1.2,
    price: 60,
    colors: ["#ff446a", "#fe7c96"],
    armorPiercing: false,
    targets: ["ground"],
    rotationSpeed: 3,
    barrelWidth: 4,
    barrelLength: 9,
  },
  {
    type: "sniper",
    label: "Sniper",
    damagePerShot: 180,
    fireRate: 0.5,
    radius: 3,
    price: 80,
    colors: ["#13cbff", "#66ddfe"],
    armorPiercing: false,
    targets: ["ground"],
    rotationSpeed: 3,
    barrelWidth: 3,
    barrelLength: 12,
  },
  {
    type: "cannon",
    label: "Cannon",
    damagePerShot: 360,
    fireRate: 0.5,
    radius: 2,
    price: 100,
    colors: ["#972ce8", "#b569ee"],
    armorPiercing: true,
    targets: ["ground"],
    rotationSpeed: 3,
    barrelWidth: 4,
    barrelLength: 11,
  },
  {
    type: "anti-air",
    label: "Anti-Air",
    damagePerShot: 80,
    fireRate: 2,
    radius: 2,
    price: 60,
    colors: ["#ff41ff", "#ff87ff"],
    armorPiercing: false,
    targets: ["air"],
    rotationSpeed: 3,
    barrelWidth: 5,
    barrelLength: 7,
  },
];
