import { TowerBlueprint } from "../state/TowerBlueprint";

export const towerBlueprints: TowerBlueprint[] = [
  {
    type: "turret",
    damagePerShot: 25,
    shootsEveryNthTick: 25,
    radius: 1.5,
    cost: 50,
    colors: ["#008A7B", "#4DB5AC"],
    armorPiercing: false,
    targets: ["air", "ground"],
    rotationSpeed: 3,
    barrelWidth: 4,
    barrelLength: 10,
  },
  {
    type: "flamethrower",
    damagePerShot: 1.6,
    shootsEveryNthTick: 1,
    radius: 1.2,
    cost: 60,
    colors: ["#E53734", "#E37370"],
    armorPiercing: false,
    targets: ["ground"],
    rotationSpeed: 4,
    barrelWidth: 4,
    barrelLength: 8,
  },
  {
    type: "sniper",
    damagePerShot: 250,
    shootsEveryNthTick: 150,
    radius: 3,
    cost: 80,
    colors: ["#49A550", "#7DC584"],
    armorPiercing: false,
    targets: ["ground"],
    rotationSpeed: 8,
    barrelWidth: 3,
    barrelLength: 12,
  },
  {
    type: "canon",
    damagePerShot: 400,
    shootsEveryNthTick: 150,
    radius: 2,
    cost: 100,
    colors: ["#2086E4", "#64B5F5"],
    armorPiercing: true,
    targets: ["ground"],
    rotationSpeed: 3,
    barrelWidth: 5,
    barrelLength: 12,
  },
  {
    type: "anti-air",
    damagePerShot: 50,
    shootsEveryNthTick: 20,
    radius: 2,
    cost: 60,
    colors: ["#0EBBBF", "#4DD0E1"],
    armorPiercing: false,
    targets: ["air"],
    rotationSpeed: 4,
    barrelWidth: 6,
    barrelLength: 6,
  },
];
