import { TowerBlueprint } from "../state/TowerBlueprint";

export const towerBlueprints: TowerBlueprint[] = [
  {
    type: "turret",
    damagePerShot: 25,
    shootsEveryNthTick: 25,
    radius: 1.5,
    cost: 50,
    colors: ["#e5e500", "#ffff19"],
    armorPiercing: false,
    targets: ["air", "ground"],
    rotationSpeed: 3,
    barrelWidth: 4,
    barrelLength: 10,
  },
  {
    type: "flamethrower",
    damagePerShot: 1.6,
    shootsEveryNthTick: 1,
    radius: 1.2,
    cost: 60,
    colors: ["#ff41ff", "#ff87ff"],
    armorPiercing: false,
    targets: ["ground"],
    rotationSpeed: 4,
    barrelWidth: 4,
    barrelLength: 8,
  },
  {
    type: "sniper",
    damagePerShot: 250,
    shootsEveryNthTick: 150,
    radius: 3,
    cost: 80,
    colors: ["#00d89a", "#19ffbd"],
    armorPiercing: false,
    targets: ["ground"],
    rotationSpeed: 8,
    barrelWidth: 3,
    barrelLength: 12,
  },
  {
    type: "canon",
    damagePerShot: 400,
    shootsEveryNthTick: 150,
    radius: 2,
    cost: 100,
    colors: ["#972ce8", "#b569ee"],
    armorPiercing: true,
    targets: ["ground"],
    rotationSpeed: 3,
    barrelWidth: 5,
    barrelLength: 12,
  },
  {
    type: "anti-air",
    damagePerShot: 50,
    shootsEveryNthTick: 20,
    radius: 2,
    cost: 60,
    colors: ["#13cbff", "#56daff"],
    armorPiercing: false,
    targets: ["air"],
    rotationSpeed: 4,
    barrelWidth: 6,
    barrelLength: 6,
  },
];
